# Generated by Django 6.1.1 on 2026-10-03 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                (
                    "ga4_property_id",
                    models.CharField(
                        blank=True,
                        help_text="Digits only, e.g. 312345678",
                        max_length=32,
                    ),
                ),
                (
                    "ads_customer_id",
                    models.CharField(
                        blank=True, help_text="Digits only, no dashes", max_length=16
                    ),
                ),
                (
                    "ads_manager_id",
                    models.CharField(
                        blank=True,
                        help_text="MCC id if accessed through a manager",
                        max_length=16,
                    ),
                ),
                ("currency_code", models.CharField(blank=True, max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True, related_name="clients", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdsCampaignDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("campaign_id", models.BigIntegerField()),
                ("campaign_name", models.CharField(max_length=255)),
                ("campaign_status", models.CharField(max_length=32)),
                ("channel_type", models.CharField(max_length=32)),
                ("impressions", models.BigIntegerField()),
                ("clicks", models.BigIntegerField()),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Account currency (cost_micros / 1e6)",
                        max_digits=14,
                    ),
                ),
                ("conversions", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "conversions_value",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.client"
                    ),
                ),
            ],
            options={
                "db_table": "ads_campaign_daily",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("client", "date", "campaign_id"),
                        name="ads_campaign_daily_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Ga4Daily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("session_source", models.CharField(max_length=255)),
                ("session_medium", models.CharField(max_length=255)),
                ("device_category", models.CharField(max_length=32)),
                ("sessions", models.IntegerField()),
                ("total_users", models.IntegerField()),
                ("new_users", models.IntegerField()),
                ("engaged_sessions", models.IntegerField()),
                ("key_events", models.DecimalField(decimal_places=2, max_digits=14)),
                ("total_revenue", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.client"
                    ),
                ),
            ],
            options={
                "db_table": "ga4_daily",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "client",
                            "date",
                            "session_source",
                            "session_medium",
                            "device_category",
                        ),
                        name="ga4_daily_uniq",
                    )
                ],
            },
        ),
    ]
