# Generated by Django 6.1.1 on 2026-10-03 08:32

import django.db.models.deletion
import pgvector.django.vector
from pgvector.django import VectorExtension
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),  # CREATE EXTENSION IF NOT EXISTS vector (needed before the embedding column)
        migrations.CreateModel(
            name="CacheEntry",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("question", models.TextField()),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(dimensions=1536, null=True),
                ),
                ("data_version", models.CharField(max_length=40)),
                ("prompt_version", models.CharField(max_length=16)),
                ("model", models.CharField(max_length=64)),
                ("response", models.JSONField()),
                ("hit_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.client"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QueryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("sql", models.TextField(blank=True)),
                ("status", models.CharField(max_length=16)),
                ("error", models.TextField(blank=True)),
                ("answer", models.TextField(blank=True)),
                ("retries", models.SmallIntegerField(default=0)),
                ("latency_ms", models.IntegerField(default=0)),
                ("timings", models.JSONField(default=dict)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("cost_usd", models.FloatField(default=0)),
                ("cache_hit", models.CharField(blank=True, max_length=8)),
                ("flagged", models.BooleanField(default=False)),
                ("feedback", models.SmallIntegerField(blank=True, null=True)),
                ("model", models.CharField(blank=True, max_length=64)),
                ("prompt_version", models.CharField(blank=True, max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="data.client",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
